### ISSUE TITLE
Potential deadlock in sd.internal.instance.Cache ?

### ISSUE THREAD

**Issue by huangjunwen** [go-kit/kit#626]
`Cache.Update` holds a lock and calls `registry.broadcast` which can be blocked if any one of the receive channels is not ready:

```
func (r registry) broadcast(event sd.Event) {
    for c := range r {
        c <- event
    }
}
```

But if at the same time the receiver does not want to listen to it anymore and calls `Cache.Deregister` which in turn waits for the lock, this will cause a deadlock, isn't it ?

**Comment by peterbourgon** [comment]
Can you write a failing test?

**Comment by yurishkuro** [comment]
I don't think this qualifies as a deadlock - you're saying _externa_ calls to cache might be blocked. If you're registering a channel you are not listening to, then it's a client error.

The alternative is to use async send to channels, which may lead to data loss.

**Comment by huangjunwen** [comment]
Hi, here is a simplified test version. Basically it emulates a sd backend with several updates in a short time, if any listener can't not keep up and deregister, it will cause deadlock.  

```
func TestDeadlock(t *testing.T) {
    c := NewCache()
    wg := &sync.WaitGroup{}
    wg.Add(2)
    go func(wg *sync.WaitGroup, c *Cache) {
        // this emulate the outside sd backend loop with several updates
        c.Update(sd.Event{
            Instances: []string{"localhost:1234"},
        })
        c.Update(sd.Event{
            Instances: []string{"localhost:1235"},
        })
        // c.Update(...)
        wg.Done()
    }(wg, c)
    go func(wg *sync.WaitGroup, c *Cache) {
        // this listener register to the cache to get instances, do something with it for quit a long time
        // then deregister
        ch := make(chan sd.Event, 1)
        c.Register(ch)
        <-ch
        time.Sleep(500 * time.Millisecond)
        c.Deregister(ch)
        wg.Done()
    }(wg, c)
    wg.Wait()

}
```

panic:
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200a0000, 0x114919f, 0xc, 0x1150b38, 0x1070201)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200a0000)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200a0000, 0xc42003dde0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc42000a1c0, 0x11f97c0, 0x3, 0x3, 0xc4200160f0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42003df18, 0xc42003df70)
	/usr/local/go/src/testing/testing.go:921 +0x111
main.main()
	github.com/go-kit/kit/sd/internal/instance/_test/_testmain.go:48 +0xdb

goroutine 19 [semacquire]:
sync.runtime_Semacquire(0xc4200ae05c)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4200ae050)
	/usr/local/go/src/sync/waitgroup.go:131 +0x72
github.com/go-kit/kit/sd/internal/instance.TestDeadlock(0xc4200b80f0)
	/Users/jayven/gowork/src/github.com/go-kit/kit/sd/internal/instance/cache_test.go:105 +0x11a
testing.tRunner(0xc4200b80f0, 0x1150b38)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 20 [chan send]:
github.com/go-kit/kit/sd/internal/instance.registry.broadcast(0xc4200aa0f0, 0xc4200bc010, 0x1, 0x1, 0x0, 0x0)
	/Users/jayven/gowork/src/github.com/go-kit/kit/sd/internal/instance/cache.go:73 +0xba
github.com/go-kit/kit/sd/internal/instance.(*Cache).Update(0xc4200a4050, 0xc4200bc010, 0x1, 0x1, 0x0, 0x0)
	/Users/jayven/gowork/src/github.com/go-kit/kit/sd/internal/instance/cache.go:38 +0x1a9
github.com/go-kit/kit/sd/internal/instance.TestDeadlock.func1(0xc4200ae050, 0xc4200a4050)
	/Users/jayven/gowork/src/github.com/go-kit/kit/sd/internal/instance/cache_test.go:89 +0x1a8
created by github.com/go-kit/kit/sd/internal/instance.TestDeadlock
	/Users/jayven/gowork/src/github.com/go-kit/kit/sd/internal/instance/cache_test.go:84 +0xe0

goroutine 21 [semacquire]:
sync.runtime_SemacquireMutex(0xc4200a4054, 0x1148100)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc4200a4050)
	/usr/local/go/src/sync/mutex.go:134 +0xee
sync.(*RWMutex).Lock(0xc4200a4050)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/go-kit/kit/sd/internal/instance.(*Cache).Deregister(0xc4200a4050, 0xc4200ac120)
	/Users/jayven/gowork/src/github.com/go-kit/kit/sd/internal/instance/cache.go:63 +0x31
github.com/go-kit/kit/sd/internal/instance.TestDeadlock.func2(0xc4200ae050, 0xc4200a4050)
	/Users/jayven/gowork/src/github.com/go-kit/kit/sd/internal/instance/cache_test.go:102 +0x93
created by github.com/go-kit/kit/sd/internal/instance.TestDeadlock
	/Users/jayven/gowork/src/github.com/go-kit/kit/sd/internal/instance/cache_test.go:95 +0x10c
exit status 2
FAIL	github.com/go-kit/kit/sd/internal/instance	1.012s
```

**Comment by yurishkuro** [comment]
I think the pattern you're applying is fundamentally incorrect. When you register a channel, you *should be already listening on it*, i.e. register / deregister should not be happening in the same go-routine as the one reading from the channel.  I.e. if you move the channel listening to a separate go-routine, then there would be no deadlock:
```
    ch := make(chan sd.Event, 1)
    go func() {
        for _ := <- ch {
             // do something, even sleep(500ms)
        }
    }
    go func(wg *sync.WaitGroup, c *Cache) {
        // this listener register to the cache to get instances, do something with it for quit a long time
        // then deregister
        c.Register(ch)
        time.Sleep(500 * time.Millisecond)
        c.Deregister(ch)
        close(ch)  // after unregister!!!
        wg.Done()
    }(wg, c)
```

**Comment by huangjunwen** [comment]
@yurishkuro Hmmm... you are right. This implies that the channel passed in should be always available to consume events before deregister. I think the document can add some hints about this. I was wrongly using this in my connection logic: register a channel with 1 buffer slot to get all the instances immediately then deregister.
